services:
    daan_fizz_buzz.example:
        class: Daan\FizzBuzzBundle\Controller\DefaultController
        arguments:
            - "@templating"
            - "@daan_fizz_buzz.fizz_buzz_service"

    daan_fizz_buzz.fizz_buzz_service:
        class: Daan\FizzBuzzBundle\Service\FizzBuzzService

